language: ruby
rvm: 2.4.5
before_install:
- gem install bundler:2.1.4
- bundle install
script:
- asciidoctor README.adoc -o index.html
after_success:
- ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - secure: DViwZ/BfeWkBcpwXfaw3pusQ3ygSU8BxEWk6e8HDWVHbND/O7I8lAkcbopSV4MIZcEZFidH7KZ45zezkraOOs52jjelr83y0Ol6vZTcw7i+DKPwT/Yj7BZlINHpaqZ3rO2zZ5hpGxNYW/HyFV5IIwXHQkEmirKzWx1o4NhHV4wTlWvrm6DNXASzgGxOQz1llfuYV20MlYFQ1qbjt8cZokMJMDzEDLF7j8tPl6SHuqjmHaIUGr9VGe6S1MFzhPFjNY8+vORrp/n4jVuZQ2nIQJrQxNxcLXpYOYW40inbUg/t/dUmH7+j8dLg4OvPWDQJyYpzwhV7EXQLDXnvTfqS/mRqAw/3/08wQLdpAWTyt8n0OjfWDMN4GIiHpW144ik68FQetR8PhFIUExEqxMDDsOFcssdqp9mbMWXmvdXQGqANuOLGHDkF3ZAjCGky84Yk0vZfGokNSzrqIrq2i2nWCjJnCqR6jJqosoCYAWpOdXbDiIj1nmFpkc2eIYqHNFWJdskS6PFNdne2J+N79sRlIpK2MWFGcbi14d0no+qeM3heQ1X9/zXIC2CXD+pURyQVPjzz5ubP/PhUhjZKngn8gSaUfZWVc4K2t3GzQpGDgaDNZG2X5WgZisKbcdrXbsWdGisL610FHcs2aGwjJvbmbJQir1y7sbWheakcxIjjix3g=
