name: update github pages
on:
  push:
    branches:
      - master
jobs:
  build-docs:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false          
      - name: run asciidoctor
        uses: docker://asciidoctor/docker-asciidoctor
        with:
          args: asciidoctor index.adoc -o index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
